version: "3.7"

services:
  ssci:
    image: mike0sv/ssci:latest
    restart: unless-stopped
    env_file:
      - template.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./repo:${PWD}/repo