name: Build docker

on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: pre-commit/action@v2.0.0

  build:
    runs-on: [ ubuntu-latest ]
    needs:
      - pre-commit
    steps:
      - uses: actions/checkout@main
      - name: Build image
        run: make build
