name: Build docker

on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@main
      - name: Build image
        run: make build
