name: Publish on Docker Hub

on:
  release:
    types: [ published ]

jobs:
  build_and_pub:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Login to docker.io
        run: echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - uses: actions/checkout@master
      - name: Build image
        run: make release
